### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jonbrennecke** [mazondo/gravatarjs#3]
Hey, this is an excellent implementation, but as of right now I couldn't tell if you've licensed this.  Could I suggest one of many [open source licenses](https://github.com/blog/1530-choosing-an-open-source-license)?

Thanks!

**Comment by dantman** [comment]
+1

**Comment by mazondo** [comment]
worst library response ever, sorry guys just saw your issue.  I've added an MIT license, which is what I thought it was all along
